name: Compile Arduino Sketch

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1
        with:
          version: 0.29.0

      - name: Install Arduino core
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr

      - name: Compile Sketch
        run: |
          arduino-cli compile --fqbn arduino:avr:uno demo_serial_device.ino/demo_serial_device.ino.ino